from collections import deque

lista = [1, 2, 3, 4, 5, 6, 7, 8, 9, 10]
de = deque(lista)
print(type(de))
print()
de.append(100)
de.appendleft(1000)
print(de)
print()
de.pop()
print("de dopo pop ->", de)
de.popleft()
print("de dopo popleft ->", de)
print()
print("indice prima occorrenza numero 4", de.index(4))
print()
print("inserisco 1200 posizione indice 4")
de.insert(4, 1200)
print(de)
print()
print("Conto la frequenza di 3", de.count(3))
print()
print("rimuovo la prima occorrenza di 1200")
de.remove(1200)
print(de)
print()
print("Estendo la lista a destra")
de.extend([20, 200, 2000])
print("Estendo la lista a sinistra")
de.extendleft([30, 300, 3000])
print(de)
print()
print("Riporto la lista all'originale...")
de.remove(30)
de.remove(300)
de.remove(3000)
de.remove(20)
de.remove(200)
de.remove(2000)
print(de)
print()
print("Sposto gli ultimi 3 elementi a sinistra")
de.rotate(3)
print(de)
print("Sposto i primi 3 elementi a destra")
de.rotate(-3)
de.rotate(-3)
print(de)
print()
print("Reverse della lista")
de.rotate(3)
de.reverse()
print(de)
