version: '1.0'

services:
    monitorapa:
        image: monitorapa
        build:
            context: .
            dockerfile: ./Dockerfile

        volumes:
            - ./out:./check/out
        #  - ./cli:/usr/src/app/cli
        #  - ./check:/usr/src/app/check
        restart: unless-stopped
